services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: whatsapp_clone
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - whatsapp-clone
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-clone
    command:
      - "start-dev"

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local

